// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1uCr5F-oe_rqVyLmJSx943zZtkPmAwSk',
    appId: '1:392367566065:web:3ae5715cb3fa8ffc688d50',
    messagingSenderId: '392367566065',
    projectId: 'flame-id-app-0',
    authDomain: 'flame-id-app-0.firebaseapp.com',
    storageBucket: 'flame-id-app-0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA32J2TPi7R6GQhEuvFTOaZ61hnyXADoiM',
    appId: '1:392367566065:android:952e88a92967f25d688d50',
    messagingSenderId: '392367566065',
    projectId: 'flame-id-app-0',
    storageBucket: 'flame-id-app-0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPlom7QZxBmNxxJt975jjaohXa9oQKiS0',
    appId: '1:392367566065:ios:a774cd31ecb2dd3d688d50',
    messagingSenderId: '392367566065',
    projectId: 'flame-id-app-0',
    storageBucket: 'flame-id-app-0.firebasestorage.app',
    iosBundleId: 'dev.coderave.flame-id-app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPlom7QZxBmNxxJt975jjaohXa9oQKiS0',
    appId: '1:392367566065:ios:a774cd31ecb2dd3d688d50',
    messagingSenderId: '392367566065',
    projectId: 'flame-id-app-0',
    storageBucket: 'flame-id-app-0.firebasestorage.app',
    iosBundleId: 'dev.coderave.flame-id-app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1uCr5F-oe_rqVyLmJSx943zZtkPmAwSk',
    appId: '1:392367566065:web:5a3767f48b814795688d50',
    messagingSenderId: '392367566065',
    projectId: 'flame-id-app-0',
    authDomain: 'flame-id-app-0.firebaseapp.com',
    storageBucket: 'flame-id-app-0.firebasestorage.app',
  );
}
