name: flame_id_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: 3.8.0
  flutter: 3.32.0

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # Supabase
  supabase_flutter: ^2.9.1

  # State Management
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  riverpod_annotation: ^2.6.1

  # Routing
  go_router: ^15.2.4

  # Forui
  forui: ^0.14.0
  forui_assets: ^0.14.0
  forui_hooks: ^0.14.0

  # UI
  pinput: ^5.0.1

  # Deep Links
  app_links: ^6.4.0

  # Helpers
  dartz: ^0.10.1
  equatable: ^2.0.7
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linting
  flutter_lints: ^6.0.0
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5

  # Generators
  build_runner: ^2.4.15
  riverpod_generator: ^2.6.5
  go_router_builder: ^3.0.1

flutter:
  uses-material-design: true

  assets:
  
    - images/logo.png